load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "image",
    srcs = [
        "insecure.go",
        "manager.go",
    ],
    importpath = "uml-container/internal/image",
    visibility = ["//:__subpackages__"],
    deps = [
        "//internal/filesystem",
        "//internal/state",
        "//internal/tarutil",
        "@com_github_google_go_containerregistry//pkg/crane",
        "@org_golang_x_sys//unix",
    ],
)

go_test(
    name = "image_test",
    srcs = ["manager_test.go"],
    embed = [":image"],
    deps = ["//internal/state"],
)
