load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "tarutil",
    srcs = ["tarutil.go"],
    importpath = "uml-container/internal/tarutil",
    visibility = ["//:__subpackages__"],
    deps = ["@org_golang_x_sys//unix"],
)

go_test(
    name = "tarutil_test",
    srcs = ["tarutil_test.go"],
    embed = [":tarutil"],
)
