load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "egress",
    srcs = [
        "gateway.go",
        "mitm.go",
    ],
    importpath = "uml-container/internal/network/egress",
    visibility = ["//:__subpackages__"],
    deps = ["//internal/audit"],
)

go_test(
    name = "egress_test",
    srcs = [
        "edge_test.go",
        "gateway_test.go",
        "rule_matcher_test.go",
    ],
    embed = [":egress"],
    deps = ["//internal/audit"],
)
