load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "uidalloc",
    srcs = ["uidalloc.go"],
    importpath = "uml-container/internal/uidalloc",
    visibility = ["//:__subpackages__"],
    deps = ["@org_golang_x_sys//unix"],
)

go_test(
    name = "uidalloc_test",
    srcs = ["uidalloc_test.go"],
    embed = [":uidalloc"],
)
