#!/usr/bin/env bash
# install.sh — idempotent bare-metal installer for PVM (agentpvm).
#
# Usage:
#   ./deploy/install.sh                 # install into /usr/local/bin + systemd
#   PREFIX=/opt/pvm ./deploy/install.sh # custom install prefix
#   ./deploy/install.sh --uninstall     # remove binaries, units, env file
#   ./deploy/install.sh --docker        # print docker compose instructions
#
# No docker required. All checks are offline.
set -euo pipefail

PREFIX="${PREFIX:-/usr/local/bin}"
ENV_DIR="/etc/pvm"
ENV_FILE="$ENV_DIR/pvm.env"
STATE_ROOT="${PVM_STATE_ROOT:-/var/lib/pvm/state}"
AUDIT_ROOT="${PVM_AUDIT_ROOT:-/var/lib/pvm/audit}"
CGROUP_ROOT="${PVM_CGROUP_ROOT:-/var/lib/pvm/cgroup}"
UNIT_DIR="/etc/systemd/system"
REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

log()  { printf '\033[1;32m[install]\033[0m %s\n' "$*"; }
warn() { printf '\033[1;33m[warn]\033[0m %s\n' "$*"; }
err()  { printf '\033[1;31m[error]\033[0m %s\n' "$*" >&2; }

need_root() {
  if [[ "$(id -u)" -ne 0 ]]; then
    err "this mode must run as root (systemd unit + /usr/local/bin install)"
    exit 1
  fi
}

# ---------------------------------------------------------------- preflight
preflight() {
  local ok=1

  # go toolchain (optional: binaries may be prebuilt and dropped in $PREFIX)
  if command -v go >/dev/null 2>&1; then
    local minor
    minor="$(go version | sed -n 's/.*go1\.\([0-9]*\).*/\1/p')"
    if [[ "$minor" =~ ^[0-9]+$ ]] && [[ "$minor" -lt 23 ]]; then
      warn "go 1.$minor found; the build needs go 1.23+ — install a newer toolchain or prebuild binaries"
      ok=0
    else
      log "go toolchain ok: $(go version)"
    fi
  else
    warn "go not found — binaries will NOT be built; prebuild agentpvm and put it in $PREFIX"
  fi

  # disk space: >= 2 GiB on the filesystem backing /var/lib
  local avail_kb
  avail_kb="$(df -Pk /var/lib 2>/dev/null | awk 'NR==2 {print $4}')"
  if [[ "$avail_kb" =~ ^[0-9]+$ ]] && [[ "$avail_kb" -lt $((2 * 1024 * 1024)) ]]; then
    err "insufficient disk: $((avail_kb / 1024)) MiB free on /var/lib, need >= 2048 MiB"
    ok=0
  else
    log "disk space ok ($((avail_kb / 1024)) MiB free on /var/lib)"
  fi

  # ports
  local port
  for port in 8080 3000; do
    if command -v ss >/dev/null 2>&1; then
      if ss -ltn "sport = :$port" 2>/dev/null | grep -q LISTEN; then
        warn "port $port already in use — stop the listener or change the unit's -port flag"
        ok=0
      else
        log "port $port free"
      fi
    else
      warn "ss not available; skipping port $port check"
    fi
  done

  # services must not run as root
  if id pvm >/dev/null 2>&1; then
    log "service user 'pvm' exists"
  else
    warn "user 'pvm' missing: creating it (system account, no login shell)"
    useradd --system --home-dir /var/lib/pvm --create-home --shell /usr/sbin/nologin pvm
  fi

  [[ $ok -eq 1 ]] || { err "preflight failed"; exit 1; }
}

# ------------------------------------------------------------------ env file
write_env_file() {
  umask 077
  mkdir -p "$ENV_DIR"
  if [[ -f "$ENV_FILE" ]]; then
    log "$ENV_FILE already exists — keeping it (idempotent)"
  else
    local secret
    secret="$(openssl rand -hex 32 2>/dev/null || head -c 32 /dev/urandom | od -An -tx1 | tr -d ' \n')"
    {
      echo "# generated by deploy/install.sh on $(date -Is)"
      echo "API_SECRET=$secret"
      echo "PVM_STATE_ROOT=$STATE_ROOT"
      echo "PVM_AUDIT_ROOT=$AUDIT_ROOT"
      echo "PVM_CGROUP_ROOT=$CGROUP_ROOT"
    } > "$ENV_FILE"
    log "wrote $ENV_FILE (mode 0600) with a fresh API_SECRET — SAVE the secret, it is never shown again"
  fi
  chown root:pvm "$ENV_FILE" 2>/dev/null || true
  chmod 0600 "$ENV_FILE"
}

# ------------------------------------------------------------------- install
do_install() {
  need_root
  preflight
  write_env_file

  mkdir -p "$STATE_ROOT" "$AUDIT_ROOT" "$CGROUP_ROOT" /var/lib/pvm/bin
  chown -R pvm:pvm /var/lib/pvm
  chmod 0700 /var/lib/pvm "$STATE_ROOT" "$AUDIT_ROOT"

  if command -v go >/dev/null 2>&1; then
    log "building agentpvm + umlctl from $REPO_ROOT"
    mkdir -p "$PREFIX"
    (cd "$REPO_ROOT" && CGO_ENABLED=0 go build -trimpath -o "$PREFIX/agentpvm" ./cmd/agentpvm)
    (cd "$REPO_ROOT" && CGO_ENABLED=0 go build -trimpath -o "$PREFIX/umlctl" ./cmd/umlctl)
  fi
  [[ -x "$PREFIX/agentpvm" ]] || { err "$PREFIX/agentpvm missing and go unavailable"; exit 1; }

  if command -v systemctl >/dev/null 2>&1; then
    log "installing systemd units"
    install -m 0644 "$REPO_ROOT/deploy/systemd/agentpvm-api.service"   "$UNIT_DIR/"
    install -m 0644 "$REPO_ROOT/deploy/systemd/agentpvm-webui.service" "$UNIT_DIR/"
    systemctl daemon-reload
    systemctl enable agentpvm-api.service agentpvm-webui.service
    log "enabled agentpvm-api.service agentpvm-webui.service (not started — run: systemctl start agentpvm-api agentpvm-webui)"
  else
    warn "systemctl not found — units not installed; run the binaries manually"
  fi

  log "install complete: $PREFIX/agentpvm, $PREFIX/umlctl, $ENV_FILE"
}

# ----------------------------------------------------------------- uninstall
do_uninstall() {
  need_root
  if command -v systemctl >/dev/null 2>&1; then
    systemctl stop agentpvm-api.service agentpvm-webui.service 2>/dev/null || true
    systemctl disable agentpvm-api.service agentpvm-webui.service 2>/dev/null || true
    rm -f "$UNIT_DIR/agentpvm-api.service" "$UNIT_DIR/agentpvm-webui.service"
    systemctl daemon-reload
  fi
  rm -f "$PREFIX/agentpvm" "$PREFIX/umlctl"
  if [[ -f "$ENV_FILE" ]]; then
    warn "keeping $ENV_FILE and /var/lib/pvm (state + audit ledger); remove manually if desired"
  fi
  log "uninstall complete"
}

# -------------------------------------------------------------------- docker
do_docker() {
  cat <<'EOF'
Docker mode (no root needed on the build host):

  1. cp deploy/pvm.env.example deploy/.env && edit API_SECRET
     (generate: openssl rand -hex 32)
  2. docker compose -f deploy/docker-compose.yml --env-file deploy/.env build
  3. docker compose -f deploy/docker-compose.yml --env-file deploy/.env up -d
  4. curl -s http://localhost:8080/healthz

If CI already built webui/.output:
  docker compose ... build --build-arg WEBUI_PREBUILT=1
EOF
}

# usage echoes the Usage block from the script header.
usage() {
  cat <<'EOF'
install.sh — idempotent bare-metal installer for PVM (agentpvm).

Usage:
  ./deploy/install.sh                 # install into /usr/local/bin + systemd
  PREFIX=/opt/pvm ./deploy/install.sh # custom install prefix
  ./deploy/install.sh --uninstall     # remove binaries, units, env file
  ./deploy/install.sh --docker        # print docker compose instructions
  ./deploy/install.sh --help          # show this help
EOF
}

case "${1:-}" in
  --uninstall) do_uninstall ;;
  --docker)    do_docker ;;
  "")          do_install ;;
  -h|--help)   usage ;;
  *)           err "unknown option: $1 (try --help)"; exit 2 ;;
esac
