load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "volume",
    srcs = [
        "binary.go",
        "builtin.go",
        "manager.go",
        "plugin.go",
        "store.go",
    ],
    importpath = "uml-container/internal/volume",
    visibility = ["//:__subpackages__"],
    deps = ["//internal/fsjson"],
)

go_test(
    name = "volume_test",
    srcs = [
        "binary_test.go",
        "volume_test.go",
    ],
    embed = [":volume"],
)
