load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "vhost",
    srcs = ["backend.go"],
    importpath = "uml-container/internal/vhost",
    visibility = ["//:__subpackages__"],
    deps = [
        "//internal/cow",
        "//internal/state",
        "//internal/vhost/vu",
    ],
)

go_test(
    name = "vhost_test",
    srcs = ["backend_test.go"],
    embed = [":vhost"],
    deps = ["//internal/state"],
)
