load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "ebpf",
    srcs = ["loader.go"],
    importpath = "uml-container/internal/ebpf",
    visibility = ["//:__subpackages__"],
    deps = ["@com_github_cilium_ebpf//:go_default_library"],
)

go_test(
    name = "ebpf_test",
    srcs = ["loader_test.go"],
    embed = [":ebpf"],
)
