load("@rules_go//go:def.bzl", "go_binary", "go_library")

go_library(
    name = "umlctl_lib",
    srcs = ["main.go"],
    importpath = "uml-container/cmd/umlctl",
    visibility = ["//visibility:private"],
    deps = [
        "//internal/config",
        "//internal/container",
        "//internal/image",
        "//internal/network",
        "//internal/spec",
        "//internal/state",
        "//internal/uml",
    ],
)

go_binary(
    name = "umlctl",
    embed = [":umlctl_lib"],
    visibility = ["//visibility:public"],
)
