load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "template",
    srcs = [
        "build.go",
        "store.go",
    ],
    importpath = "uml-container/internal/template",
    visibility = ["//:__subpackages__"],
    deps = [
        "//internal/fsjson",
        "//internal/image",
        "//internal/metrics",
        "@com_github_google_uuid//:go_default_library",
    ],
)

go_test(
    name = "template_test",
    srcs = ["store_test.go"],
    embed = [":template"],
)
